### ISSUE TITLE
Multiple extensions to domain

### ISSUE THREAD

**Issue by InitRoot** [nyxgeek/onedrive_user_enum#1]
Firstly lovely script. The code doesn't cater for multiple extensions on the domain names e.g. .co.za or gov.us etc.

The attached code will fix the issue.

[onedrive_enum.txt](https://github.com/nyxgeek/onedrive_user_enum/files/5089539/onedrive_enum.txt)

**Comment by nyxgeek** [comment]
Thanks so much! I'll review and update shortly unless you wanted to do a PR and be listed as contributor to this project? Your call. Thanks again!
